pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                // Переконайся, що Jenkins виконує ці команди у правильному контексті
                bat "mvn clean compile"
                bat "mvn package"
            }
            post {
                success {
                    archiveArtifacts artifacts: 'target/*.jar', allowEmptyArchive: true
                }
                failure {
                    echo 'Build failed!'
                }
            }
        }
    }
}
